### ISSUE TITLE
fix: readthedocs build

### ISSUE THREAD

**Issue by Avsecz** [Avsecz/concise#7]

**Comment by Avsecz** [comment]
Problem in using python 2.7 instead of 3.5?
```
Running Sphinx v1.3.5
making output directory...
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/envs/latest/local/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 52, in <module>
    import concise
  File "/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/checkouts/latest/concise/__init__.py", line 10, in <module>
    from .kmer import best_kmers
  File "/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/checkouts/latest/concise/kmer.py", line 7, in <module>
    from concise.get_data import seq_pad_and_trim
ImportError: No module named get_data

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/concise-bio/checkouts/latest/concise/kmer.py", line 7, in <module>
    from concise.get_data import seq_pad_and_trim
ImportError: No module named get_data
The full traceback has been saved in /tmp/sphinx-err-SpRZwE.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
